### ISSUE TITLE
sort collections in alpha order

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#59] opened 2017-10-04 01:31 UTC
Hi, 

The collections on all the institution pages, should sort alphabetically a-z

eg on this page: http://test-prl.library.ucla.edu/institution?name=University%20of%20Hawaii%20at%20Manoa

**Comment by markmatney** [comment] 2017-10-04 02:12
I made a duplicate of this before checking if it already existed, but it has more information than this ticket so I'm closing this one. Please refer to https://github.com/pier2marketing/ucla-prrla/issues/61 instead

**Closed as completed by markmatney** 2017-10-04 02:12 UTC
